#!/bin/sh

cd ~/.vim/

mkdir ~/.vim/bundle
mkdir ~/.vim/backup

if [ -f '../.vimrc' ]; then
  backup_filename=~/.vimrc.bak.`date +%s`;
  echo ".vimrc found. move it to $backup_filename"
  mv ~/.vimrc $backup_filename;
fi
ln -s ~/.vim/vimrc ~/.vimrc

if [ -f '../.gvimrc' ]; then
  backup_filename=~/.gvimrc.bak.`date +%s`;
  echo ".gvimrc found. move it to $backup_filename"
  mv ~/.gvimrc $backup_filename;
fi
ln -s ~/.vim/gvimrc ~/.gvimrc

if [ -f '../.gitconfig' ]; then
  backup_filename=~/.gitconfig.bak.`date +%s`;
  echo ".gitconfig found. move it to $backup_filename"
  mv ~/.gitconfig $backup_filename;
fi
ln -s ~/.vim/gitconfig ~/.gitconfig

if [ -f '../.zshrc' ]; then
  backup_filename=~/.zshrc.bak.`date +%s`;
  echo ".zshrc found. move it to $backup_filename"
  mv ~/.zshrc $backup_filename;
fi
ln -s ~/.vim/zshrc ~/.zshrc

if [ -f '../.gemrc' ]; then
  backup_filename=~/.gemrc.bak.`date +%s`;
  echo ".gemrc found. move it to $backup_filename"
  mv ~/.gemrc $backup_filename;
fi
ln -s ~/.vim/gemrc ~/.gemrc

git clone http://github.com/gmarik/vundle.git ~/.vim/bundle/vundle

vim -c :BundleInstall

