#!/bin/sh

DOTFILES_DIR=~/.config/dotfiles
cd $DOTFILES_DIR

mkdir -p ~/.vim/bundle
mkdir -p ~/.vim/backup

if [ -f ~/.vimrc ]; then
  backup_filename=~/.vimrc.bak;
  echo ".vimrc found. move it to $backup_filename"
  mv ~/.vimrc $backup_filename;
  mkdir -p ~/.vim/pack
fi
ln -s $DOTFILES_DIR/vimrc ~/.vimrc

if [ -f ~/.bashrc ]; then
  backup_filename=~/.bashrc.bak;
  echo ".bashrc found. move it to $backup_filename"
  mv ~/.bashrc $backup_filename;
fi
ln -s $DOTFILES_DIR/bashrc ~/.bashrc

if [ -f ~/.bashrc.d ]; then
  backup_filename=~/.bashrc.d.bak;
  echo ".bashrc.d found. move it to $backup_filename"
  mv ~/.bashrc.d $backup_filename;
fi
ln -s $DOTFILES_DIR/bashrc.d ~/.bashrc.d



if [ -f ~/.gitconfig ]; then
  backup_filename=~/.gitconfig.bak;
  echo ".gitconfig found. move it to $backup_filename"
  mv ~/.gitconfig $backup_filename;
fi
ln -s $DOTFILES_DIR/gitconfig ~/.gitconfig

if [ -f ~/.tmux.conf ]; then
  backup_filename=~/.tmux.conf.bak;
  echo ".tmux.conf found. move it to $backup_filename"
  mv ~/.tmux.conf $backup_filename;
fi
ln -s $DOTFILES_DIR/tmux.conf ~/.tmux.conf

if [ -f ~/.bundle/config ]; then
  backup_filename=~/.bundle/config.bak;
  echo ".bundle/config found. move it to $backup_filename"
  mv ~/.bundle/config $backup_filename;
fi
mkdir -p ~/.bundle
ln -s $DOTFILES_DIR/bundleconfig ~/.bundle/config

