#!/bin/sh

cd ~/.vim/

mkdir ~/.vim/bundle
mkdir ~/.vim/backup

if [ -f '../.vimrc' ]; then
  backup_filename=~/.vimrc.bak.`date +%s`;
  echo ".vimrc found. move it to $backup_filename"
  mv ~/.vimrc $backup_filename;
fi
ln -s ~/.vim/vimrc ~/.vimrc

if [ -f '../.gvimrc' ]; then
  backup_filename=~/.gvimrc.bak.`date +%s`;
  echo ".gvimrc found. move it to $backup_filename"
  mv ~/.gvimrc $backup_filename;
fi
ln -s ~/.vim/gvimrc ~/.gvimrc

if [ -f '../.gitconfig' ]; then
  backup_filename=~/.gitconfig.bak.`date +%s`;
  echo ".gitconfig found. move it to $backup_filename"
  mv ~/.gitconfig $backup_filename;
fi
ln -s ~/.vim/gitconfig ~/.gitconfig

if [ -f '../.zshrc' ]; then
  backup_filename=~/.zshrc.bak.`date +%s`;
  echo ".zshrc found. move it to $backup_filename"
  mv ~/.zshrc $backup_filename;
fi
ln -s ~/.vim/zshrc ~/.zshrc

if [ -f '../.gemrc' ]; then
  backup_filename=~/.gemrc.bak.`date +%s`;
  echo ".gemrc found. move it to $backup_filename"
  mv ~/.gemrc $backup_filename;
fi
ln -s ~/.vim/gemrc ~/.gemrc

if [ -f '../.tmux.conf' ]; then
  backup_filename=~/.tmux.conf.bak.`date +%s`;
  echo ".tmux.conf found. move it to $backup_filename"
  mv ~/.tmux.conf $backup_filename;
fi
ln -s ~/.vim/tmux.conf ~/.tmux.conf

if [ -f '../.irssi/config' ]; then
  backup_filename=~/.irssi/config.bak.`date +%s`;
  echo ".irssi/config found. move it to $backup_filename"
  mv ~/.irssi/config $backup_filename;
fi
ln -s ~/.irssi/config ~/irssi.conf

if [ -f '../.bundle/config' ]; then
  backup_filename=~/.bundle/config.bak.`date +%s`;
  echo ".bundle/config found. move it to $backup_filename"
  mv ~/.bundle/config $backup_filename;
fi
ln -s ~/.vim/bundleconfig ~/.bundle/config



git clone http://github.com/gmarik/vundle.git ~/.vim/bundle/vundle

vim -c :BundleInstall

